a = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Ésta em maiúsculas? ', a.isupper())
print('Esta em minúscula? ', a.islower())
print('Esta capitalizada? ', a.istitle())
